.podman-setup: &podman-setup
  - zypper --non-interactive install jq podman
  - usermod --add-subuids 100000-165535 --add-subgids 100000-165535 $(id -nu)
  - podman login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $REGISTRY

check_version_collisions:
  stage: check_version
  rules:
    - changes:
        - package.json
  script:
    - *podman-setup
    - |
      PACKAGE_VERSION=`jq -r .version package.json`
      PACKAGE_NAME=`jq -r .name package.json`

      readarray -t VERSIONS < <(podman search $REGISTRY/$IMAGE_NAMESPACE/ui-extension-$PACKAGE_NAME --list-tags --format {{.Tag}})

      echo -e "Checking for version collisions with Extension version: ${PACKAGE_VERSION}"
      for version in ${VERSIONS[@]}; do
        if [[ ${version} == ${PACKAGE_VERSION} ]]; then
          echo "Cannot overwrite production image version ${version} since it already exists."
          podman logout $REGISTRY
          exit 1
        fi
      done

      echo -e "Published image not found for version ${PACKAGE_VERSION}, continuing build..."
  tags:
    - linux

build_and_release:
  stage: build_catalog
  rules:
    - changes:
        - package.json
  script:
    - *podman-setup
    - zypper addrepo https://download.opensuse.org/repositories/devel:languages:nodejs/SLE_12_SP5/devel:languages:nodejs.repo
    - zypper --non-interactive --no-gpg-checks refresh
    - zypper --non-interactive install go git nodejs14 npm helm
    - YQ_URL="https://github.com/mikefarah/yq/releases/download/v4.35.2/yq_linux_amd64"
    - curl -sLf ${YQ_URL} -o /usr/bin/yq && chmod +x /usr/bin/yq
    - npm install -g --unsafe-perm yarn
    - yarn
    - yarn publish-pkgs -cl -r $REGISTRY -o $IMAGE_NAMESPACE
    - podman push `podman images -f reference!=registry.suse.com/bci/bci-base --format "{{index .Names 0}}"`
    - podman logout $REGISTRY
  tags:
    - linux
