export const HCI = {
  VM:                 'kubevirt.io.virtualmachine',
  VMI:                'kubevirt.io.virtualmachineinstance',
  VMIM:               'kubevirt.io.virtualmachineinstancemigration',
  VM_TEMPLATE:        'harvesterhci.io.virtualmachinetemplate',
  VM_VERSION:         'harvesterhci.io.virtualmachinetemplateversion',
  IMAGE:              'harvesterhci.io.virtualmachineimage',
  SSH:                'harvesterhci.io.keypair',
  VOLUME:             'harvesterhci.io.volume',
  USER:               'harvesterhci.io.user',
  SETTING:            'harvesterhci.io.setting',
  UPGRADE:            'harvesterhci.io.upgrade',
  BACKUP:             'harvesterhci.io.virtualmachinebackup',
  RESTORE:            'harvesterhci.io.virtualmachinerestore',
  NODE_NETWORK:       'network.harvesterhci.io.nodenetwork',
  CLUSTER_NETWORK:    'network.harvesterhci.io.clusternetwork',
  SUPPORT_BUNDLE:     'harvesterhci.io.supportbundle',
  NETWORK_ATTACHMENT: 'harvesterhci.io.networkattachmentdefinition',
  CLUSTER:            'harvesterhci.io.management.cluster',
  DASHBOARD:          'harvesterhci.io.dashboard',
  BLOCK_DEVICE:       'harvesterhci.io.blockdevice',
  CLOUD_TEMPLATE:     'harvesterhci.io.cloudtemplate',
  HOST:               'harvesterhci.io.host',
  VERSION:            'harvesterhci.io.version',
  MANAGED_CHART:      'harvesterhci.io.managedchart',
  SNAPSHOT:           'harvesterhci.io.volumesnapshot',
  VM_SNAPSHOT:        'harvesterhci.io.vmsnapshot',
  ALERTMANAGERCONFIG: 'harvesterhci.io.monitoring.alertmanagerconfig',
  CLUSTER_FLOW:       'harvesterhci.io.logging.clusterflow',
  CLUSTER_OUTPUT:     'harvesterhci.io.logging.clusteroutput',
  FLOW:               'harvesterhci.io.logging.flow',
  OUTPUT:             'harvesterhci.io.logging.output',
  STORAGE:            'harvesterhci.io.storage',
  KSTUNED:            'node.harvesterhci.io.ksmtuned',
  PCI_DEVICE:         'devices.harvesterhci.io.pcidevice',
  PCI_CLAIM:          'devices.harvesterhci.io.pcideviceclaim',
  VLAN_CONFIG:        'network.harvesterhci.io.vlanconfig',
  VLAN_STATUS:        'network.harvesterhci.io.vlanstatus',
};

export const VOLUME_SNAPSHOT = 'snapshot.storage.k8s.io.volumesnapshot';
