import * as vue3 from 'vue';
import $ from 'jquery';
import JSZip from 'jszip';
import jsyaml from 'js-yaml';
import dynamicLoader from '@rancher/dynamic';

// Load any plugins that are present as npm modules
// The 'dynamic' module is generated by the rancher-dynamic-modules Vite plugin

export default function({
  app,
  store,
  $axios,
  redirect,
  $extension,
}, inject) {
  if (dynamicLoader) {
    dynamicLoader($extension);
  }

  // Global libraries - allows us to externalise these to reduce extension bundle size
  // Extensions built as ESM still may reference these globals via their rollup externals config
  window.Vue = vue3;
  window.$ = $;
  window.__jszip = JSZip;
  window.__jsyaml = jsyaml;
}
