name: Setup Node
description: Setup node, including yarn

runs:
  using: 'composite'
  steps:
    - name: Setup yarn
      shell: bash
      run: ./scripts/setup-yarn
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: '.nvmrc'
        cache: 'yarn'
