name: Setup UI Env
description: Setup node, yarn install

runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: ./.github/actions/setup-node

    - name: Install packages
      shell: bash
      run: yarn install:ci
