{
 "title": "Kubewarden",
 "description": "Official dashboard for Kubewarden metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "policy_name" }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 0, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Accepted requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(kubewarden_policy_evaluations_total{accepted=\"true\"}[$__rate_interval]))*100/sum(rate(kubewarden_policy_evaluations_total[$__rate_interval]))",
     "legendFormat": "Accepted Requests"
    }
   ]
  },
  {
   "title": "Rejected requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(kubewarden_policy_evaluations_total{accepted=\"false\"}[$__rate_interval]))*100/sum(rate(kubewarden_policy_evaluations_total[$__rate_interval]))",
     "legendFormat": "Rejected Requests"
    }
   ]
  },
  {
   "title": "Mutated requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(kubewarden_policy_evaluations_total{mutated=\"true\"}[$__rate_interval]))*100/sum(rate(kubewarden_policy_evaluations_total[$__rate_interval]))",
     "legendFormat": "Mutated Requests"
    }
   ]
  },
  {
   "title": "Total accepted requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubewarden_policy_evaluations_total{accepted=\"true\"})"
    }
   ]
  },
  {
   "title": "Total rejected requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubewarden_policy_evaluations_total{accepted=\"false\"})"
    }
   ]
  },
  {
   "title": "Total mutated requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubewarden_policy_evaluations_total{mutated=\"true\"})"
    }
   ]
  }
 ]
}