---
kind: pipeline
name: test

trigger:
  event:
  - push
  - pull_request
  - tag

platform:
  os: linux
  arch: amd64

steps:
- name: test
  pull: default
  image: node:12
  commands:
  - scripts/ci

---
kind: pipeline
name: docker-branch

depends_on:
- test

trigger:
  ref:
  - "refs/heads/master"
  - "refs/heads/*-dev"
  - "refs/heads/release-*"
  event:
  - push

platform:
  os: linux
  arch: amd64

steps:
- name: gate
  pull: default
  image: node:12
  commands:
  - ./scripts/build-upload-gate

- name: docker-image
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    tag: ${DRONE_BRANCH}
    repo: rancherlabs/dashboard
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

---
kind: pipeline
name: docker-tag

depends_on:
- test

trigger:
  event:
  - tag

platform:
  os: linux
  arch: amd64

steps:
- name: docker-image
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    tag: ${DRONE_TAG}
    repo: rancherlabs/dashboard
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

---
kind: pipeline
name: hosted-master

depends_on:
- test

trigger:
  ref:
  - "refs/heads/master"
  event:
  - push

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: default
  image: node:12
  commands:
  - ./scripts/build-hosted

- name: upload-gate
  pull: default
  image: node:12
  commands:
  - ./scripts/build-upload-gate

- name: upload
  pull: default
  image: plugins/gcs
  settings:
    acl:
    - allUsers:READER
    cache_control: "no-cache,must-revalidate"
    source: dist/latest
    target: releases.rancher.com/dashboard/latest
    token:
      from_secret: google_auth_key

---
kind: pipeline
name: hosted-branch

depends_on:
- test

trigger:
  ref:
  - "refs/heads/*-dev"
  - "refs/heads/release-*"
  event:
  - push

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: default
  image: node:12
  commands:
  - ./scripts/build-hosted

- name: upload
  pull: default
  image: plugins/gcs
  settings:
    acl:
    - allUsers:READER
    cache_control: "no-cache,must-revalidate"
    source: dist/${DRONE_BRANCH}
    target: releases.rancher.com/dashboard/${DRONE_BRANCH}
    token:
      from_secret: google_auth_key

---
kind: pipeline
name: hosted-tag

depends_on:
- test

trigger:
  event:
  - tag

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: default
  image: node:12
  commands:
  - ./scripts/build-hosted

- name: upload
  pull: default
  image: plugins/gcs
  settings:
    acl:
    - allUsers:READER
    cache_control: "no-cache,must-revalidate"
    source: dist/${DRONE_TAG}
    target: releases.rancher.com/dashboard/${DRONE_TAG}
    token:
      from_secret: google_auth_key

---
kind: pipeline
name: embedded-master

depends_on:
- test

trigger:
  ref:
  - "refs/heads/master"
  event:
  - push

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: default
  image: node:12
  commands:
  - ./scripts/build-embedded

- name: upload-gate
  pull: default
  image: node:12
  commands:
  - ./scripts/build-upload-gate

- name: upload
  pull: default
  image: plugins/gcs
  settings:
    acl:
    - allUsers:READER
    cache_control: "no-cache,must-revalidate"
    source: dist/${DRONE_BRANCH}.tar.gz
    target: releases.rancher.com/dashboard/latest.tar.gz
    token:
      from_secret: google_auth_key

---
kind: pipeline
name: embedded-branch

depends_on:
- test

trigger:
  ref:
  - "refs/heads/*-dev"
  - "refs/heads/release-*"
  event:
  - push

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: default
  image: node:12
  commands:
  - ./scripts/build-embedded

- name: upload
  pull: default
  image: plugins/gcs
  settings:
    acl:
    - allUsers:READER
    cache_control: "no-cache,must-revalidate"
    source: dist/${DRONE_BRANCH}.tar.gz
    target: releases.rancher.com/dashboard/${DRONE_BRANCH}.tar.gz
    token:
      from_secret: google_auth_key

---
kind: pipeline
name: embedded-tag

depends_on:
- test

trigger:
  event:
  - tag

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: default
  image: node:12
  commands:
  - ./scripts/build-embedded

- name: upload
  pull: default
  image: plugins/gcs
  settings:
    acl:
    - allUsers:READER
    cache_control: "no-cache,must-revalidate"
    source: dist/${DRONE_TAG}.tar.gz
    target: releases.rancher.com/dashboard/${DRONE_TAG}.tar.gz
    token:
      from_secret: google_auth_key
