---
kind: pipeline
name: test

trigger:
  event:
  - push
  - tag

platform:
  os: linux
  arch: amd64

steps:
- name: test
  pull: default
  image: node:14
  commands:
  - scripts/ci

---
kind: pipeline
name: hosted-master

depends_on:
- test

trigger:
  ref:
  - "refs/heads/master"
  event:
  - push

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: default
  image: node:14
  commands:
  - ./scripts/build-hosted

- name: upload-gate
  pull: default
  image: node:14
  commands:
  - ./scripts/build-upload-gate

- name: upload
  pull: default
  image: plugins/gcs
  settings:
    acl:
    - allUsers:READER
    cache_control: "no-cache,must-revalidate"
    source: dist/latest
    target: releases.rancher.com/dashboard/latest
    token:
      from_secret: google_auth_key

---
kind: pipeline
name: hosted-branch

depends_on:
- test

trigger:
  ref:
  - "refs/heads/*-dev"
  - "refs/heads/release-*"
  event:
  - push

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: default
  image: node:14
  commands:
  - ./scripts/build-hosted

- name: upload
  pull: default
  image: plugins/gcs
  settings:
    acl:
    - allUsers:READER
    cache_control: "no-cache,must-revalidate"
    source: dist/${DRONE_BRANCH}
    target: releases.rancher.com/dashboard/${DRONE_BRANCH}
    token:
      from_secret: google_auth_key

---
kind: pipeline
name: hosted-tag

depends_on:
- test

trigger:
  event:
  - tag

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: default
  image: node:14
  commands:
  - ./scripts/build-hosted

- name: upload
  pull: default
  image: plugins/gcs
  settings:
    acl:
    - allUsers:READER
    cache_control: "no-cache,must-revalidate"
    source: dist/${DRONE_TAG}
    target: releases.rancher.com/dashboard/${DRONE_TAG}
    token:
      from_secret: google_auth_key

---
kind: pipeline
name: embedded-master

depends_on:
- test

trigger:
  ref:
  - "refs/heads/master"
  event:
  - push

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: default
  image: node:14
  environment:
    EMBED_PKG: https://releases.rancher.com/harvester-ui/plugin/harvester-1.0.3.tar.gz
  commands:
  - ./scripts/build-embedded

- name: upload-gate
  pull: default
  image: node:14
  commands:
  - ./scripts/build-upload-gate

- name: upload
  pull: default
  image: plugins/gcs
  settings:
    acl:
    - allUsers:READER
    cache_control: "no-cache,must-revalidate"
    source: dist/${DRONE_BRANCH}.tar.gz
    target: releases.rancher.com/dashboard/latest.tar.gz
    token:
      from_secret: google_auth_key

---
kind: pipeline
name: embedded-branch

depends_on:
- test

trigger:
  ref:
  - "refs/heads/*-dev"
  - "refs/heads/release-*"
  event:
  - push

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: default
  image: node:14
  environment:
    EMBED_PKG: https://releases.rancher.com/harvester-ui/plugin/harvester-1.0.3.tar.gz
  commands:
  - ./scripts/build-embedded

- name: upload
  pull: default
  image: plugins/gcs
  settings:
    acl:
    - allUsers:READER
    cache_control: "no-cache,must-revalidate"
    source: dist/${DRONE_BRANCH}.tar.gz
    target: releases.rancher.com/dashboard/${DRONE_BRANCH}.tar.gz
    token:
      from_secret: google_auth_key

---
kind: pipeline
name: embedded-tag

depends_on:
- test

trigger:
  event:
  - tag

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: default
  image: node:14
  environment:
    EMBED_PKG: https://releases.rancher.com/harvester-ui/plugin/harvester-1.0.3.tar.gz
  commands:
  - ./scripts/build-embedded

- name: upload
  pull: default
  image: plugins/gcs
  settings:
    acl:
    - allUsers:READER
    cache_control: "no-cache,must-revalidate"
    source: dist/${DRONE_TAG}.tar.gz
    target: releases.rancher.com/dashboard/${DRONE_TAG}.tar.gz
    token:
      from_secret: google_auth_key

# ---

# kind: pipeline
# name: fossa

# steps:
# - name: fossa
#   image: rancher/drone-fossa:latest
#   failure: ignore
#   settings:
#     api_key:
#       from_secret: FOSSA_API_KEY
#   when:
#     instance:
#       - drone-publish.rancher.io