FROM node:lts AS builder

RUN mkdir /src
WORKDIR /src
COPY . .
RUN yarn --pure-lockfile install
ENV ROUTER_BASE="/dashboard"
RUN yarn run build --spa

FROM rancher/rancher:v2.6.3
WORKDIR /var/lib/rancher
RUN rm -rf /usr/share/rancher/ui-dashboard/dashboard*
COPY --from=builder /src/dist /usr/share/rancher/ui-dashboard/dashboard
