# Builder
FROM node:16-alpine3.12 as builder
WORKDIR /dashboard
COPY package.json /src/
COPY yarn.lock /src/
RUN yarn --pure-lockfile install

COPY . /src
RUN yarn build

# Production Build
FROM nginx:1.20-alpine
COPY --from=builder /dashboard/dist /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
