FROM node:lts AS builder

RUN mkdir /src
WORKDIR /src

RUN apk update && apk upgrade

COPY package.json /src/
COPY yarn.lock /src/

RUN yarn --pure-lockfile install

COPY . /src
ENV ROUTER_BASE="/dashboard"
RUN yarn run build --spa

FROM rancher/rancher:v2.6.3
WORKDIR /var/lib/rancher
RUN rm -rf /usr/share/rancher/ui-dashboard/dashboard*
COPY --from=builder /src/dist /usr/share/rancher/ui-dashboard/dashboard
