import Steve from '@shell/plugins/steve/steve-class.js';
import { steveClassJunkObject } from './utils/steve-mocks';

describe('class: Steve', () => {
  describe('given custom resource keys', () => {
    const customResource = steveClassJunkObject;

    it('should keep internal keys', () => {
      const steve = new Steve(customResource, {
        getters:     { schemaFor: () => ({ linkFor: jest.fn() }) },
        dispatch:    jest.fn(),
        rootGetters: { 'i18n/t': jest.fn() },
      });

      expect({ ...steve }).toStrictEqual(customResource);
    });

    describe('method: save', () => {
      it('should remove all the internal keys', async() => {
        const dispatch = jest.fn();
        const steve = new Steve(customResource, {
          getters:     { schemaFor: () => ({ linkFor: jest.fn() }) },
          dispatch,
          rootGetters: { 'i18n/t': jest.fn() },
        });

        const expectation = {
          type:     customResource.type,
          metadata: {
            resourceVersion:            'whatever',
            fields:                     'whatever',
            clusterName:                'whatever',
            deletionGracePeriodSeconds: 'whatever',
            generateName:               'whatever',
            ownerReferences:            'whatever',
          },
          spec: { versions: {} }
        };

        await steve.save();

        const opt = {
          data:    expectation,
          headers: {
            accept:         'application/json',
            'content-type': 'application/json',
          },
          method: 'post',
          url:    undefined,
        };

        // Data sent should have been cleaned
        expect(dispatch).toHaveBeenCalledWith('request', { opt, type: customResource.type });

        // Original workload model should remain unchanged
        expect({ ...steve }).toStrictEqual(customResource);
      });
    });

    describe('method: notifyGeneratedName', () => {
      const createSteve = (value: any) => {
        const dispatch = jest.fn();
        const t = jest.fn((key, params) => `${ key } ${ JSON.stringify(params) }`);
        const steve = new Steve({ ...customResource, ...value }, {
          getters:     { schemaFor: () => ({ linkFor: jest.fn() }) },
          dispatch,
          rootGetters: { 'i18n/t': t },
        });

        Object.defineProperty(steve, 'typeDisplay', { get: () => 'CustomResourceDefinition' });

        return {
          steve, dispatch, t
        };
      };

      it.each([
        ['a namespaced resource', 'default/test-generated-abc123', 'test-generated-abc123'],
        ['a cluster scoped resource', 'simple-id', 'simple-id'],
      ])('should show the growl with the generated name for %p', (_, id, expectedId) => {
        const { steve, dispatch, t } = createSteve({ id, metadata: { generateName: 'test-generated-' } });

        steve.notifyGeneratedName();

        expect(t).toHaveBeenCalledWith('generic.autogeneratedCreated.title', { resource: 'CustomResourceDefinition' });
        expect(t).toHaveBeenCalledWith('generic.autogeneratedCreated.message', { id: expectedId, resource: 'CustomResourceDefinition' });
        expect(dispatch).toHaveBeenCalledWith('growl/success', {
          title:   `generic.autogeneratedCreated.title ${ JSON.stringify({ resource: 'CustomResourceDefinition' }) }`,
          message: `generic.autogeneratedCreated.message ${ JSON.stringify({ id: expectedId, resource: 'CustomResourceDefinition' }) }`,
          timeout: 3000
        }, { root: true });
      });

      it.each([
        ['without generateName', { id: 'default/test-regular-name', metadata: { name: 'test-regular-name' } }],
        ['without id', { id: undefined, metadata: { generateName: 'test-generated-' } }],
      ])('should not show the growl %s', (_, value) => {
        const { steve, dispatch } = createSteve(value);

        steve.notifyGeneratedName();

        expect(dispatch).toHaveBeenCalledTimes(0);
      });
    });
  });
});
