import Steve from '@shell/plugins/steve/steve-class.js';
import { steveClassJunkObject } from './utils/steve-mocks';

describe('class: Steve', () => {
  describe('given custom resource keys', () => {
    const customResource = steveClassJunkObject;

    it('should keep internal keys', () => {
      const steve = new Steve(customResource, {
        getters:     { schemaFor: () => ({ linkFor: jest.fn() }) },
        dispatch:    jest.fn(),
        rootGetters: { 'i18n/t': jest.fn() },
      });

      expect({ ...steve }).toStrictEqual(customResource);
    });

    describe('method: save', () => {
      it('should remove all the internal keys', async() => {
        const dispatch = jest.fn();
        const steve = new Steve(customResource, {
          getters:     { schemaFor: () => ({ linkFor: jest.fn() }) },
          dispatch,
          rootGetters: { 'i18n/t': jest.fn() },
        });

        const expectation = {
          type:     customResource.type,
          metadata: {
            resourceVersion:            'whatever',
            fields:                     'whatever',
            clusterName:                'whatever',
            deletionGracePeriodSeconds: 'whatever',
            generateName:               'whatever',
            ownerReferences:            'whatever',
          },
          spec: { versions: {} }
        };

        await steve.save();

        const opt = {
          data:    expectation,
          headers: {
            accept:         'application/json',
            'content-type': 'application/json',
          },
          method: 'post',
          url:    undefined,
        };

        // Data sent should have been cleaned
        expect(dispatch).toHaveBeenCalledWith('request', { opt, type: customResource.type });

        // Original workload model should remain unchanged
        expect({ ...steve }).toStrictEqual(customResource);
      });
    });

    describe('method: notifyGeneratedName', () => {
      const createSteve = (value: any) => {
        const dispatch = jest.fn();
        const t = jest.fn((key, params) => `${ key } ${ JSON.stringify(params) }`);
        const steve = new Steve({ ...customResource, ...value }, {
          getters:     { schemaFor: () => ({ linkFor: jest.fn() }) },
          dispatch,
          rootGetters: { 'i18n/t': t },
        });

        Object.defineProperty(steve, 'typeDisplay', { get: () => 'CustomResourceDefinition' });

        return {
          steve, dispatch, t
        };
      };

      it.each([
        ['a namespaced resource', 'default/test-generated-abc123', 'test-generated-abc123'],
        ['a cluster scoped resource', 'simple-id', 'simple-id'],
      ])('should show the growl with the generated name for %p', (_, id, expectedId) => {
        const { steve, dispatch, t } = createSteve({ id, metadata: { generateName: 'test-generated-' } });

        steve.notifyGeneratedName();

        expect(t).toHaveBeenCalledWith('generic.autogeneratedCreated.title', { resource: 'CustomResourceDefinition' });
        expect(t).toHaveBeenCalledWith('generic.autogeneratedCreated.message', { id: expectedId, resource: 'CustomResourceDefinition' });
        expect(dispatch).toHaveBeenCalledWith('growl/success', {
          title:   `generic.autogeneratedCreated.title ${ JSON.stringify({ resource: 'CustomResourceDefinition' }) }`,
          message: `generic.autogeneratedCreated.message ${ JSON.stringify({ id: expectedId, resource: 'CustomResourceDefinition' }) }`,
          timeout: 3000
        }, { root: true });
      });

      it.each([
        ['without generateName', { id: 'default/test-regular-name', metadata: { name: 'test-regular-name' } }],
        ['without id', { id: undefined, metadata: { generateName: 'test-generated-' } }],
      ])('should not show the growl %s', (_, value) => {
        const { steve, dispatch } = createSteve(value);

        steve.notifyGeneratedName();

        expect(dispatch).toHaveBeenCalledTimes(0);
      });
    });
  });
});

describe('class: Steve, creating from YAML', () => {
  const yaml = 'metadata:\n  namespace: default\n  generateName: test-generated-\n';
  const response = { id: 'default/test-generated-abc12', metadata: { namespace: 'default', generateName: 'test-generated-' } };

  const createSteve = (value: any) => {
    // 'load' updates the existing model with the response, as the store does
    const dispatch = jest.fn((action, payload) => {
      if (action === 'load' && payload?.existing) {
        Object.assign(payload.existing, payload.data);
      }
    });
    const followLink = jest.fn().mockResolvedValue(response);
    const steve = new Steve(value, {
      getters:     { schemaFor: () => ({ attributes: { namespaced: true }, followLink }) },
      dispatch,
      rootGetters: { 'i18n/t': jest.fn((key) => key) },
    });

    Object.defineProperty(steve, 'typeDisplay', { get: () => 'Thing' });

    return { steve, dispatch };
  };

  it('should show the generated name growl when creating', async() => {
    const { steve, dispatch } = createSteve({ type: 'thing' });

    await steve.saveYaml(yaml);

    expect(dispatch).toHaveBeenCalledWith('growl/success', {
      title:   'generic.autogeneratedCreated.title',
      message: 'generic.autogeneratedCreated.message',
      timeout: 3000
    }, { root: true });
  });

  it('should not show the generated name growl when updating', async() => {
    const { steve, dispatch } = createSteve({ ...response, type: 'thing' });

    jest.spyOn(steve, 'followLink').mockResolvedValue(response);

    await steve.saveYaml(yaml);

    expect(dispatch).not.toHaveBeenCalledWith('growl/success', expect.anything(), expect.anything());
  });
});
