#!/bin/bash
set -e

echo "GITHUB_SHA: $GITHUB_SHA"
echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
echo "ROUTER_BASE: $ROUTER_BASE"
echo
echo "RELEASE_DIR: $RELEASE_DIR"
RELEASE_LOCATION="$RELEASE_DIR/$ARTIFACT_NAME"
echo "RELEASE_LOCATION: $RELEASE_LOCATION"
echo
echo "ARTIFACT_NAME: $ARTIFACT_NAME"
ARTIFACT_LOCATION="$OUTPUT_DIR/$ARTIFACT_NAME"
echo "ARTIFACT_LOCATION: $ARTIFACT_LOCATION"
echo
echo "OUTPUT_DIR: $OUTPUT_DIR"

# /dashboard

mkdir ${{ RELEASE_DIR }}
yarn install --frozen-lockfile
NUXT_ENV_commit=${GITHUB_SHA} NUXT_ENV_version=${GITHUB_REF_NAME} OUTPUT_DIR=ARTIFACT_LOCATION ROUTER_BASE="$ROUTER_BASE" RANCHER_ENV=desktop yarn run build --spa
tar -czf RELEASE_LOCATION.tar.gz -C ARTIFACT_LOCATION .
sha512sum RELEASE_LOCATION.tar.gz > RELEASE_LOCATION.tar.gz.sha512sum
