#!/bin/bash
set -e

BUILD_DEBUG="${BUILD_DEBUG:-}"
if [[ -n "${BUILD_DEBUG}" ]]; then
    set -x
    env
fi

cd $(dirname $0)/..

echo "Bootstrapping..."
yarn install --frozen-lockfile

source scripts/version
echo "BRANCH: ${COMMIT_BRANCH:-<none>}"
echo "TAG: ${GIT_TAG:-<none>}"
DIR=${GIT_TAG:-$COMMIT_BRANCH}

if [[ "${DIR}" == "master" ]]; then
  DIR="latest"
fi

BASE=${BASE:-https://releases.rancher.com/dashboard/${DIR}}

echo "Building for ${BASE}..."

OUTPUT_DIR=dist/${DIR}

ENV_OUTPUT="${GITHUB_OUTPUT:-"temp-env"}"
echo "BUILD_HOSTED_DIR=${OUTPUT_DIR}" >> "$ENV_OUTPUT"
echo "BUILD_HOSTED_LOCATION=${DIR}" >> "$ENV_OUTPUT"

COMMIT=${COMMIT} VERSION=${VERSION} OUTPUT_DIR=${OUTPUT_DIR} ROUTER_BASE="/dashboard/" RESOURCE_BASE="${BASE}" yarn run build

# Write the version beside the other static files at the root of the build.
# Strip the leading `v` from tags (e.g. v2.14.0-alpha7 -> 2.14.0-alpha7) to match the old Ember UI format.
echo "${VERSION#v}" > ${OUTPUT_DIR}/VERSION.txt
