#!/bin/bash
set -e

BUILD_DEBUG="${BUILD_DEBUG:-}"
if [[ -n "${BUILD_DEBUG}" ]]; then
    set -x
    env
fi

cd $(dirname $0)/..

echo "Bootstrapping..."
yarn --pure-lockfile install

echo "Linting..."
yarn run lint

echo "Testing..."
yarn run test:ci

echo "Building..."
yarn run build
