#!/usr/bin/env bash
set -x

DEPLOYMENT_NAME="rancher"
RANCHER_NAMESPACE="cattle-system"

POD_NAMES=$(kubectl get pods -n "$RANCHER_NAMESPACE" -l app="$DEPLOYMENT_NAME" -o jsonpath='{.items[*].metadata.name}')

if [ -z "$POD_NAMES" ]; then
  echo "No pods found!"
  exit 0
fi

for POD in $POD_NAMES; do
  echo "Logs for pod: $POD"
  echo "---------------------------------------------------------------------" > "$E2E_RANCHER_LOG"
  echo "Logs for pod: $POD" > "$E2E_RANCHER_LOG"
  echo "---------------------------------------------------------------------" > "$E2E_RANCHER_LOG"

  echo $POD > $E2E_RANCHER_LOG
  kubectl logs "$POD" -n "$RANCHER_NAMESPACE" --all-containers=true --prefix > "$E2E_RANCHER_LOG" 2>&1

  echo "Containers for pod: $POD" > "$E2E_RANCHER_LOG"
  kubectl get pod "$POD" -n "$RANCHER_NAMESPACE" -o jsonpath='{.spec.containers[*].name}'

done