#!/bin/bash

# Directories and folders not to replace in
GREP_EXCLUDES="--exclude-dir=.git --exclude-dir=.nuxt --exclude-dir=node_modules --exclude=rejig --exclude=nuxt.config.js"

echo "Re-jigging codebase"

DIR=$(cd $(dirname $0); cd ..; pwd)

echo $DIR

if [ "$1" == "-d" ]; then
  echo "Resetting"

  TEMP_DIR=$(mktemp -d)
  cp ${DIR}/PLUGINS.md ${TEMP_DIR}
  cp ${DIR}/scripts/rejig ${TEMP_DIR}
  cp ${DIR}/nuxt.config.js ${TEMP_DIR}
  cp ${DIR}/shell/nuxt.config.js ${TEMP_DIR}/nuxt.config.js.sh

  git reset --hard
  git clean -fd

  mv ${TEMP_DIR}/PLUGINS.md ${DIR}
  mv ${TEMP_DIR}/rejig ${DIR}/scripts
  mv ${TEMP_DIR}/nuxt.config.js ${DIR}
  mv ${TEMP_DIR}/nuxt.config.js.sh ${DIR}/shell/nuxt.config.js

  rm -rf ${TEMP_DIR}
  echo "Reset"
  exit 0
fi

function move() {
  if [ -d $1 ]; then
    echo "  > $1"
    #git mv $1/ ${SHELL}
    mv $1/ ${SHELL}
  fi
}

# Make new folders

pushd $DIR 2>&1 > /dev/null

SHELL=./shell

mkdir -p ${SHELL}

# Remove the design-system pages - we're going to use Storybook
rm -rf pages/design-system

echo "Moving folders ..."

move ./server
move ./layouts
move ./plugins
move ./utils
move ./config
move ./static
move ./middleware
move ./mixins
move ./store
move ./pages
move ./components
move ./assets

move ./chart
move ./cloud-credential
move ./detail
move ./edit
move ./list
move ./machine-config
move ./models
move ./promptRemove

move ./content

echo "Updating imports ..."

declare -a contextFolders=(
  "utils" "plugins" "config" "mixins" "store" "pages" "components" "assets" "chart"
  "cloud-credential" "content" "detail" "edit" "list" "machine-config" "models" "promptRemove")

for i in "${contextFolders[@]}"
  do
    echo "  > $i"
    grep -rl ${GREP_EXCLUDES} . -e '@/'"$i"'' | xargs -r sed -i.bak -e "s/'@\/""$i""/'@shell\/""$i""/g"
    grep -rl ${GREP_EXCLUDES} . -e '`@/'"$i"'' | xargs -r sed -i.bak -e "s/\`@\/""$i""/\`@shell\/""$i""/g"
    grep -rl ${GREP_EXCLUDES} . -e '~/'"$i"'' | xargs -r sed -i.bak -e "s/~\/""$i""/~shell\/""$i""/g"

    grep -rl ${GREP_EXCLUDES} . -e '~'"$i"'' | xargs -r sed -i.bak -e "s/~""$i""/~shell\/""$i""/g"
  done

echo "Removing any .bak files ..."
find . -type f -name "*.bak" -delete

popd 2>&1 > /dev/null

echo "All done"
