#!/usr/bin/env bash
set -x

# if we have yarn, no op
# if no yarn, install (probably running in non-containerized runners)

command_exists () {
  command -v "$1" >/dev/null 2>&1
}

if command_exists yarn; then
  echo "yarn already installed"
  yarn --version
  exit 0
fi

curl -fsSL -o ~/bin/yarn https://github.com/yarnpkg/yarn/releases/download/v1.22.17/yarn-1.22.17.js
chmod +x ~/bin/yarn
echo "~/bin" >> $GITHUB_PATH

if command_exists yarn; then
  echo "yarn installed"
  yarn --version
else
  echo "failed to install yarn"
  exit 1
fi