#!/bin/bash

if [ -z "$ARCH" ]; then
    ARCH=$(go env GOHOSTARCH)
fi

SUFFIX="-${ARCH}"

if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
        DIRTY="-dirty"
    fi

    COMMIT=$(git rev-parse --short HEAD)
    GIT_TAG=${DRONE_TAG:-$(git tag -l --contains HEAD | head -n 1)}

    if [[ -z "$DIRTY" && -n "$GIT_TAG" ]]; then
        VERSION=$GIT_TAG
    else
        VERSION="${COMMIT}${DIRTY}"
    fi

    TAG=${TAG:-${VERSION}${SUFFIX}}
fi

REPO=${REPO:-ui-plugin-server}
ORG=${ORG:-rancher}

if echo $TAG | grep -q dirty; then
    TAG=dev
fi
