# Docs for this workflow are here https://github.com/github/issue-labeler
name: Triage Labels
on:
  issues:
    types:
      - opened
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label issues
        if: "!startsWith(github.event.issue.labels.*.name, '[zube]:')"
        uses: github/issue-labeler@v2.5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml
          enable-versioned-regex: 0