name: Build Dashboard 2.8 (Release)
on:
  push:
    tags:
      - v2.8.*
      - richard-cox-2.8.patch1-drone-tag

jobs:
  build-validation:
    name: Validate Code
    uses: ./.github/workflows/build-test.yaml
  build:
    name: Build and Upload
    uses: ./.github/workflows/build-and-upload.yaml
    needs:
      - build-validation
    permissions:
      contents: 'read'
      id-token: 'write'
    with:
      CI_BUILD_TAG: ${{github.ref_name}}
