name: Notify docs team

on:
  issues:
      types: 
        - labeled

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
        - uses: jenschelkopf/issue-label-notification-action@1.3
          with:
             recipients: |
                  release-note=@martyav
             message:
                  'Hello {recipients} - please add this issue to the Rancher release notes.'
