name: gh-project-integration
on:
  pull_request:
    types: [ opened, reopened, edited, closed ]

jobs:
    if: ${{ github.repository_owner == 'rancher' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Use Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: '.nvmrc'
    - name: Write GitHub Event
      run: |
        cat $GITHUB_EVENT_PATH  > event.json
    - name: Upload event data so it can be used in the processor workflow
      uses: actions/upload-artifact@v6
      with:
        name: pr-gh-project-event
        path: event.json
        if-no-files-found: error
        retention-days: 1
        compression-level: 9
