name: Pull Request Validation

on:
  pull_request:
    branches:
      - master
      - 'release-*'
    types:
      - "labeled"
      - "unlabeled"
      - "synchronize"
  workflow_run:
    branches:
      - master
      - 'release-*'
    workflows: ["zube-integration"]
    types:
      - completed

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validation for Milestone
        if: ${{ github.event.pull_request.milestone == null }}
        uses: actions/github-script@v5
        with:
          script: |
            core.setFailed( '❌ Pull request must have a Milestone. Assign one and toggle a label to re-run' )
