name: rancher-components
on:
  pull_request:
    paths:
      - 'pkg/rancher-components/**/*'
    branches:
      - master

jobs:
  validate-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 1
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version-file: '.nvmrc'
      
      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Verify build
        run: yarn build:lib

  validate-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 1
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version-file: '.nvmrc'
      
      - name: Install packages
        run: yarn install --frozen-lockfile
      
      - name: Run linters
        run: yarn lint:lib
