name: Build and Release Rancher Dashboard - Rancher Desktop Embed

on:
  push:
    tags:
        - 'desktop-v*'

env:
  OUTPUT_DIR: dist
  RELEASE_DIR: release
  ARTIFACT_NAME: rancher-dashboard-desktop-embed
  STEVE_API: "https://127.0.0.1:9443"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: false
    
    - uses: actions/setup-node@v2
      with:
        node-version: '12.x'
    
    - name: Install & Build
      run: |
        mkdir ${{ env.RELEASE_DIR }}
        yarn install --frozen-lockfile
        NUXT_ENV_commit=${GITHUB_SHA} NUXT_ENV_version=${GITHUB_REF_NAME} OUTPUT_DIR=${{ env.OUTPUT_DIR }}/${{ env.ARTIFACT_NAME }} API=${{ env.STEVE_API }} RESOURCE_BASE=${{ env.STEVE_API }} ROUTER_BASE='/dashboard' RANCHER_ENV=desktop yarn run build --spa
        tar -czf ${{ env.RELEASE_DIR }}/${{ env.ARTIFACT_NAME }}.tar.gz -C ${{ env.OUTPUT_DIR }}/${{ env.ARTIFACT_NAME }} .
        sha512sum ${{ env.RELEASE_DIR }}/${{ env.ARTIFACT_NAME }}.tar.gz > ${{ env.RELEASE_DIR }}/${{ env.ARTIFACT_NAME }}.tar.gz.sha512sum

    - name: Upload Build
      uses: actions/upload-artifact@v2
      with:
        path: ${{ env.RELEASE_DIR}}/${{ env.ARTIFACT_NAME }}*
        name: ${{ env.ARTIFACT_NAME }}
        if-no-files-found: error
  
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        persist-credentials: false
    - name: Download build
      uses: actions/download-artifact@v2
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: build
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Upload Release Assets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload ${{ env.RELEASE_VERSION }} build/${{ env.ARTIFACT_NAME }}.tar.gz build/${{ env.ARTIFACT_NAME }}.tar.gz.sha512sum
