name: Build and Release Rancher Dashboard - Rancher Epinio Standalone

on:
  push:
    tags:
        - 'epinio-standalone-v*'

env:
  OUTPUT_DIR: dist
  RELEASE_DIR: release
  ARTIFACT_NAME: rancher-dashboard-epinio-standalone-embed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: false

    - uses: actions/setup-node@v2
      with:
        node-version: '12.x'

    - name: Install & Build
      run:
        RANCHER_ENV=epinio EXCLUDES_PKG=rancher-components ./.github/workflows/scripts/build-dashboard.sh

    - name: Upload Build
      uses: actions/upload-artifact@v2
      with:
        path: ${{ env.RELEASE_DIR}}/${{ env.ARTIFACT_NAME }}*
        name: ${{ env.ARTIFACT_NAME }}
        if-no-files-found: error

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        persist-credentials: false
    - name: Download build
      uses: actions/download-artifact@v2
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: build
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create ${{ env.RELEASE_VERSION }} --prerelease
    - name: Upload Release Assets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload ${{ env.RELEASE_VERSION }} build/${{ env.ARTIFACT_NAME }}.tar.gz build/${{ env.ARTIFACT_NAME }}.tar.gz.sha512sum
