name: temp test
on:
  push:
    branches:
      - e2e-k3s

env:
  TEST_USERNAME: admin
  TEST_PASSWORD: password
  CATTLE_BOOTSTRAP_PASSWORD: password
  TEST_BASE_URL: https://127.0.0.1:8005
  API: https://127.0.0.1
  TEST_PROJECT_ID: rancher-dashboard
  CYPRESS_API_URL: http://139.59.134.103:1234/
  TEST_RUN_ID: ${{github.run_number}}-${{github.run_attempt}}-${{github.event.pull_request.title || github.event.head_commit.message}}
  # Build the dashboard to use in tests. When set to false it will grab `latest` from CDN (useful for running e2e tests quickly)
  BUILD_DASHBOARD: false

  E2E_BUILD_DIST_NAME: dist
  E2E_BUILD_DIST_DIR: dist
  E2E_BUILD_DIST_EMBER_NAME: dist_ember
  E2E_BUILD_DIST_EMBER_DIR: dist_ember

jobs:
  e2e-ui-build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
       with:
        fetch-depth: 1
     - uses: actions/setup-node@v3
       with:
        node-version: '14.x'
        cache: 'yarn'
     - name: Install packages
       run: yarn install:ci
     - name: Build e2e
       run: yarn e2e:build
     - name: Upload e2e build
       uses: actions/upload-artifact@v4
       with:
        name: ${{ env.E2E_BUILD_DIST_NAME }}
        path: ${{ env.E2E_BUILD_DIST_DIR }}/
        if-no-files-found: error
        retention-days: 10
        compression-level: 9
     - name: Upload e2e build ember
       uses: actions/upload-artifact@v4
       with:
        name: ${{ env.E2E_BUILD_DIST_EMBER_NAME }}
        path: ${{ env.E2E_BUILD_DIST_EMBER_DIR }}/
        if-no-files-found: error
        retention-days: 10
        compression-level: 9
  test-k3s:
    needs: e2e-ui-build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Download e2e build
      uses:  actions/download-artifact@v4
      with:
        name: ${{ env.E2E_BUILD_DIST_NAME }}
        path: ${{ env.E2E_BUILD_DIST_DIR }}
    - name: Download e2e build ember
      uses:  actions/download-artifact@v4
      with:
        name: ${{ env.E2E_BUILD_DIST_EMBER_NAME }}
        path: ${{ env.E2E_BUILD_DIST_EMBER_DIR }}

    - name: Run Rancher
      run: yarn e2e:k3s
