name: Update Cloud Data
on: workflow_dispatch
jobs:
  update-cloud-data:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
    - name: Install Node Modules
      run: yarn install
    - name: Update Cloud Data
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_NAME: ${{ github.repository }}
        TARGET_BRANCH: ${{ env.target_branch }}
      run: .github/workflows/scripts/update-cloud-data.sh
