name: Update Cloud Data
on:
  # Runs every 3 days
  schedule:
    - cron: "0 0 */3 * *"
  # Can be trigger manually if needed
  workflow_dispatch:
jobs:
  update-cloud-data:
    if: github.repository_owner == 'rancher'
    runs-on: ubuntu-latest
    #permissions: write-all
    permissions:
      actions: write
      contents: write
      pull-requests: write
      id-token: write    
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
    - name: Setup env
      uses: ./.github/actions/setup
    - name: Update Cloud Data
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_NAME: ${{ github.repository }}
      run: .github/workflows/scripts/update-cloud-data.sh
