name: Check for Unexpected Milestone Change

on:
  issues:
    types: [milestoned, demilestoned]

# Restrictive baseline permissions for all jobs
permissions:
  issues: read
 
jobs:
  notify-on-milestone-change:
    if: github.repository_owner == 'rancher'
    permissions:
      issues: read
      id-token: write

    runs-on: ubuntu-latest
    env:
      ACTOR: ''
      ISSUE_TITLE: ''
      ISSUE_URL: ''
      NEW_MILESTONE: ''
      OLD_MILESTONE: ''
      APPID: ''
      PRIVATEKEY: ''
    steps:
    - name: Set Event Data
      id: event_data
      env:
        ACTION: ${{ github.event.action }}
        ISSUE_MILESTONE: ${{ github.event.issue.milestone.title }}
        SENDER_LOGIN: ${{ github.event.sender.login }}
        ISSUE_TITLE: ${{ github.event.issue.title }}
        ISSUE_URL: ${{ github.event.issue.html_url }}
      run: |
        # Generate a random delimiter to securely write multiline strings and prevent injection vulnerabilities
        del=$(openssl rand -hex 16)
        {
          if [ "$ACTION" == "milestoned" ]; then
            echo "OLD_MILESTONE=None"
            echo "NEW_MILESTONE=$ISSUE_MILESTONE"
          elif [ "$ACTION" == "demilestoned" ]; then
            echo "OLD_MILESTONE=$ISSUE_MILESTONE"
            echo "NEW_MILESTONE=None"
          fi

          echo "ACTOR=$SENDER_LOGIN"
          echo "ISSUE_URL=$ISSUE_URL"

          # Use delimiter
          echo "ISSUE_TITLE<<$del"
          echo "$ISSUE_TITLE"
          echo "$del"

        } >> "$GITHUB_ENV"

    - name: Read secrets
      uses: rancher-eio/read-vault-secrets@7282bf97898cd1c16c89f837e0bb442e6d384c89 # v3
      with:
        secrets: |
          secret/data/github/repo/${{ github.repository }}/github/app-credentials appId | APPID;
          secret/data/github/repo/${{ github.repository }}/github/app-credentials privateKey | PRIVATEKEY

    - name: Generate Token
      id: generate-token
      uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
      with:
        app-id: ${{ env.APPID }}
        private-key: ${{ env.PRIVATEKEY }}

    - name: Check Team Membership
      id: check_team
      continue-on-error: true
      if: |
        github.event.sender.login != 'rancher-ui-project-bot' &&
        github.event.sender.login != 'rancher-backport-assistant'
      env:
        GH_TOKEN: ${{ steps.generate-token.outputs.token }} # Requires org access
      run: |
        gh api --silent /orgs/rancher/teams/ui/memberships/$ACTOR

    - name: "Send Slack message if user is not a team member"
      if: steps.check_team.outcome == 'failure'
      uses: slackapi/slack-github-action@45a88b9581bfab2566dc881e2cd66d334e621e2c # v3.0.3
      with:
        payload: |
            {
              "actor": ${{ toJSON(env.ACTOR) }},
              "issue_title": ${{ toJSON(env.ISSUE_TITLE) }},
              "issue_url": ${{ toJSON(env.ISSUE_URL) }},
              "milestone_new": ${{ toJSON(env.NEW_MILESTONE) }},
              "milestone_old": ${{ toJSON(env.OLD_MILESTONE) }}
            }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WORKFLOW_MILESTONE_CHANGED_URL }}
